# Generated by Django 3.1.4 on 2021-01-07 03:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='username',
            field=models.CharField(default='Lupus', max_length=20, verbose_name='Kullanıcı Adı:'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Mesaj:'),
        ),
        migrations.AlterField(
            model_name='message',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='Messages/', verbose_name='Dosya Ekle:'),
        ),
    ]
