# Generated by Django 3.1.4 on 2021-01-06 01:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0002_auto_20210102_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilan',
            name='ilan_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Görsel'),
        ),
        migrations.AlterField(
            model_name='ilan',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
