# Generated by Django 3.1.4 on 2021-01-07 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0004_auto_20210106_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilan',
            name='ilan_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Görsel Ekle:'),
        ),
    ]
