# Generated by Django 3.1.4 on 2021-01-07 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='facebook',
            field=models.CharField(blank=True, help_text='Facebook linkinizi koyunuz.', max_length=30, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instagram',
            field=models.CharField(blank=True, help_text='Instagram linkinizi koyunuz.', max_length=30, null=True, verbose_name='İnstagram'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='Photo/', verbose_name='Profil Fotoğrafı Ekle'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter',
            field=models.CharField(blank=True, help_text='Twitter linkinizi koyunuz.', max_length=30, null=True, verbose_name='Twitter'),
        ),
    ]
